#!/bin/bash
#
# Drop-in replacement for tunctl from the old uml_utilities
# replaced by ip from the iproute2 package.
# https://bbs.archlinux.org/viewtopic.php?pid=1285079#p1285079
#
# By Alexandre de Verteuil 2013-06-06.

if ! which ip &> /dev/null; then
    echo "ip not found, is iproute2 package installed?" >&2
    exit 1
fi

while getopts d:bu:t: argument
do
    case $argument in
        d)
            ip tuntap del dev "$OPTARG" mode tap
            exit $?
            ;;
        u)
            USERARG="user $OPTARG"
            ;;
        b)
            #Brief, there is no verbose.
            ;;
        t)
            DEVNAME="dev $OPTARG"
            ;;
    esac
done

# Memorize existing tap devices.
before=$(ip tuntap list | cut -d: -f1 | sort)

# Create the new tap device.
ip tuntap add $DEVNAME mode tap $DEVNAME || exit 1

# Memorize the new list of tap devices.
after=$(ip tuntap list | cut -d: -f1 | sort)

# Spit out the name of the new device, just like tunctl would do.
echo $(comm -13 <(echo "$before") <(echo "$after"))
